#!/bin/bash

## Start config: humanoid medium on a poolgpu

# IF PARALLEL on poolgpus
is_cuda=true
i_cuda=0
N_cuda=5

# env
env_name=mujoco/humanoid/medium-v0

# offline ckpt_dir, ckpt_path, online log_dir
ckpt_dir=${root_dir}/humanoid_medium_v0_run1
ckpt_path=${ckpt_dir}/offline_ckpt
log_dir_pre=${ckpt_dir}_online_abl_pextemp

# inverse temperatures. NOTE: REMOVE 3.0 IF ALREADY RUN
# inv_temps=("1.5" "3.0" "6.0")
inv_temps=("1.5" "6.0")

# seeds
seeds=(2003530388 2454176472 4257710153)

## end config

for inv_temp in "${inv_temps[@]}";
do
    for seed in "${seeds[@]}";
    do
        if [ "$is_cuda" = true ]; then
            CUDA_VISIBLE_DEVICES=$i_cuda python main_online.py --log_dir="${log_dir_pre}_${inv_temp}_${seed}" --env_name=${env_name} --algorithm=pex --ckpt_path="$ckpt_path" --seed=$seed --inv_temperature=$inv_temp &
	    if [ "$i_cuda" -lt "$N_cuda" ]; then
		echo $i_cuda
                i_cuda=$((i_cuda+1))
	    else
		i_cuda=1
		wait
	    fi
        else
            # WARNING: ELSE IS NOT TESTED YET
            python main_online.py --log_dir="${log_dir_pre}_${inv_temp}_${seed}" --env_name=${env_name} --algorithm=pex --ckpt_path="$ckpt_path" --seed=$seed --inv_temperature=$inv_temp
        fi
    done
done
