#!/bin/bash

## Start config: hopper medium on a poolgpu

# IF PARALLEL on poolgpus
is_cuda=true
i_cuda=4

# env
env_name=mujoco/hopper/medium-v0

# offline ckpt_dir, ckpt_path, online log_dir
ckpt_dir=${root_dir}/hopper_medium_v0_run3
ckpt_path=${ckpt_dir}/offline_ckpt

log_dir_pre=${ckpt_dir}_online_abl_pextemp

# inverse temperatures. NOTE: REMOVE 3.0 IF ALREADY RUN
# inv_temps=("1.5" "3.0" "6.0")
inv_temps=("1.5" "6.0")

# seeds
seeds=($onseed1 $onseed2 $onseed3)

## end config

for inv_temp in "${inv_temps[@]}";
do
    for seed in "${seeds[@]}";
    do
        if [ "$is_cuda" = true ]; then
            CUDA_VISIBLE_DEVICES=$i_cuda python main_online.py --log_dir="${log_dir_pre}_${inv_temp}_${seed}" --env_name=${env_name} --algorithm=pex --ckpt_path="$ckpt_path" --seed=$seed --inv_temperature=$inv_temp &
	    if [ "$i_cuda" -lt 6 ]; then
                i_cuda=$((i_cuda+1))
	    else
		i_cuda=1
		wait
	    fi
        else
            # WARNING: ELSE IS NOT TESTED YET
            python main_online.py --log_dir="${log_dir_pre}_${inv_temp}_${seed}" --env_name=${env_name} --algorithm=pex --ckpt_path="$ckpt_path" --seed=$seed --inv_temperature=$inv_temp
        fi
    done
done
